name = "Damysos"
uuid = "fd5f980c-983e-4c87-a5d0-4feb611f7d72"
authors = ["Wolfgang Hogger <wolfgang.hogger@ur.de>"]
version = "1.0.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqGPU = "071ae1c0-96b5-11e9-1965-c90190d839ea"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Richardson = "708f8203-808e-40c0-ba2d-98a6953ed40d"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.10"           # >= 1.10, < 2.0        

Accessors          = "0.1"   # v0.1.43
Adapt              = "4"     # v4.4.0
ArgCheck           = "2"     # v2.5.0
ArgParse           = "1"     # v1.2.0
BenchmarkTools     = "1"     # v1.6.3
CSV                = "0.10"  # v0.10.15
CUDA               = "5"     # v5.9.5
CairoMakie         = "0.15"  # v0.15.8
ColorSchemes       = "3"     # v3.31.0
Cthulhu            = "2"     # v2.17.6
DSP                = "0.8"   # v0.8.4
DataFrames         = "1"     # v1.8.1
DataStructures     = "0.18"  # v0.18.22
DiffEqGPU          = "3"     # v3.9.0
DifferentialEquations = "7"  # v7.17.0
Documenter         = "1"     # v1.16.1
EnumX              = "1"     # v1.0.5
FFTW               = "1"     # v1.10.0
FiniteDifferences  = "0.12"  # v0.12.33
HDF5               = "0.17"  # v0.17.2
Infiltrator        = "1"     # v1.9.4
Interpolations     = "0.16"  # v0.16.2
JuliaFormatter     = "2"     # v2.2.0
KernelAbstractions = "0.9"   # v0.9.39
LoggingExtras      = "1"     # v1.2.0
Makie              = "0.24"  # v0.24.8
OrdinaryDiffEq     = "6"     # v6.103.0
ProgressLogging    = "0.1"   # v0.1.6
Reexport           = "1"     # v1.2.2
Revise             = "3"     # v3.12.2
Richardson         = "1"     # v1.4.2
SpecialFunctions   = "2"     # v2.6.1
StaticArrays       = "1"     # v1.9.15
TerminalLoggers    = "0.1"   # v0.1.7
Unitful            = "1"     # v1.26.0

# extras
Test               = "1"     # stdlib, so this line is not necessary
# CUDA_Runtime_jll = "5"     


[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
